In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
import time

a = list(range(1000000))
b = list(range(1000000))

start = time.time()
result = [x + y for x,y in zip(a,b)]
end = time.time()
print("Python List Time: ",end - start)


Python List Time:  0.10732078552246094


In [6]:
import numpy as np
import time
a_np = np.arange(1000000)
b_np = np.arange(1000000)
start = time.time()
result_np =a_np+b_np
end = time.time()
print("NumPy Array Time:",end - start)

NumPy Array Time: 0.010473251342773438


In [8]:
a = np.array([1,2,3,4])
print("1D Array:",a)

a.shape

1D Array: [1 2 3 4]


(4,)

In [9]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__pac

In [15]:
a = np.array([[[1,1],[2,2]],
             [[3,3],[4,4]]])
print("3D Array:",a)

a.shape

3D Array: [[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]


(2, 2, 2)

In [16]:
a.ndim

3

In [13]:
a = np.array([[1,2],
             [3,4]])
print("2D Array:",a)

a.shape

2D Array: [[1 2]
 [3 4]]


(2, 2)

In [19]:
b = np.zeros((3,3), dtype = int)
print("Zeros:\n",b)

Zeros:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
c = np.ones((3,3), dtype = int)
print("Ones:\n",c)

Ones:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [21]:
d = b + c
print(d)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
(n,) = 1D array with n elements

(1, n) = 2D array with 1 row and n columns

(n, 1) = 2D array with n rows and 1 column

(n,) ≠ (n, 1) ≠ (1, n) even though they all have n total elements

In [4]:
b = np.zeros((3,3), dtype = int)
print("Zeros:\n",b)
b.ndim

Zeros:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


2

In [10]:
import numpy as np
arr = np.arange(12)
print("Original:",arr)

#slicing
print("First 5:",arr[:5])
print("First 5:",arr[-3:0])

print(arr[2:7])

#Reshape to 3*4
reshaped = arr.reshape(3,4)
print("Reshpaed 3*4:\n", reshaped)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
First 5: [0 1 2 3 4]
First 5: []
[2 3 4 5 6]
Reshpaed 3*4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
print("\nLast Column:\n",reshaped[:,-1])
print("\nLast Row:\n",reshaped[-1])


Last Column:
 [ 3  7 11]

Last Row:
 [ 8  9 10 11]


In [12]:
reshaped[0][-1] =55
reshaped

array([[ 0,  1,  2, 55],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
type(reshaped[:,-1])

numpy.ndarray

In [14]:
###Vctor operations and Broadcasting
###Vectorized operation allow fast element-wise operations
###Broadcasting enables operations between arrays of different types.

In [16]:
##two dimesnions are compatible when
##they are equal or
##one of them is 1

In [18]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print("Addition:",x+y)
print("Multiplication:",x*y)
print("Scalar Multiplication:",x*10)


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Scalar Multiplication: [10 20 30]


In [21]:
#Broadcasting example
mat = np.ones((2,3),dtype= int)
print(mat)

print("----------------------")
vec = np.array([1,2,3])
print("Broadcasted Addition:\n",mat+vec)


[[1 1 1]
 [1 1 1]]
----------------------
Broadcasted Addition:
 [[2 3 4]
 [2 3 4]]


In [23]:
#Broadcasting example
mat = np.ones((4,4),dtype= int)
print(mat)

print("----------------------")
vec = np.array([5,6,7,8])
print("Broadcasted Addition:\n",mat+vec)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
----------------------
Broadcasted Addition:
 [[6 7 8 9]
 [6 7 8 9]
 [6 7 8 9]
 [6 7 8 9]]


In [24]:
#Broadcasting example
mat = np.ones((4,4),dtype= int)
print(mat)

print("----------------------")
vec = np.array([5,6,7,8])
print("Broadcasted Multiplication:\n",mat*vec)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
----------------------
Broadcasted Multiplication:
 [[5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [28]:
#Broadcasting example
mat = np.ones((4,4),dtype= int)
print(mat)

print("----------------------")
vec = np.array([1,2,3,4])
print("Broadcasted Addition:\n",mat+vec)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
----------------------
Broadcasted Addition:
 [[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]


In [30]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Scalar multiplication:\n",arr*10)

Scalar multiplication:
 [[10 20 30]
 [40 50 60]]


In [32]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Scalar addition:\n",arr+10)

Scalar addition:
 [[11 12 13]
 [14 15 16]]


In [ ]:
###Statistical Functions
##Numpy provides built in methods to compute statistics like mean, sum and standard deviation

In [33]:
data = np.array([[80,85,90],
                 [70,75,65],
                 [88,92,95]])
print("Mean:",np.mean(data))
print("Mean:",np.sum(data))

Mean: 82.22222222222223
Mean: 740


In [35]:
print("Standard Deviation:",np.std(data))
print("Max of data:",np.max(data))
print("Min of data:",np.min(data))

Standard Deviation: 9.795438595792973
Max of data: 95
Min of data: 65


In [37]:
dir(data)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [42]:
#Mean by axis
print("Mean per student:",np.mean(data,axis = 1))
print("Mean per subject:",np.mean(data,axis = 0, dtype=int))

Mean per student: [85.         70.         91.66666667]
Mean per subject: [79 84 83]


#### Boolean Indexing and Filtering
* Use Boolean masks to filter  arrays based on conditions
* In NumPy you can pass a boolean array inside square brackets to filter the original array. This is called boolean indexing


In [45]:
scores = np.array([55, 72, 89, 45, 99, 66, 78])
high_scores = scores[scores > 70]
print("Scores > 70:", high_scores)

#find even scores
even = scores[scores%2==0]
print("Even Scores:",even)

Scores > 70: [72 89 99 78]
Even Scores: [72 66 78]


In [47]:
#find even scores
odd = scores[scores%2!=0]
print("Odd Scores:",odd)

Odd Scores: [55 89 45 99]


In [49]:
#Matrix multiplication
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[2,0],[1,2]])
result = np.dot(mat1,mat2)
print("Matrix Multiplication:\n",result)

Matrix Multiplication:
 [[ 4  4]
 [10  8]]


In [52]:
#Matrix multiplication
mat1 = np.array([[1,2,10],[3,4,11]])
mat2 = np.array([[2,0],[1,2],[5,6]])
result = np.dot(mat1,mat2)
print("Matrix Multiplication:\n",result)

Matrix Multiplication:
 [[54 64]
 [65 74]]


In [53]:
#Matrix multiplication
mat1 = np.array([[1,2,10],[3,4,11]])
mat2 = np.array([[2,0],[1,2],[5,6]])
result = np.matmul(mat2,mat1)
print("Matrix Multiplication:\n",result)

Matrix Multiplication:
 [[  2   4  20]
 [  7  10  32]
 [ 23  34 116]]


In [54]:
#Matrix multiplication
mat1 = np.array([[1,2,10],[3,4,11]])
mat2 = np.array([[2,0],[1,2],[5,6]])
result = mat2@mat1
print("Matrix Multiplication:\n",result)

Matrix Multiplication:
 [[  2   4  20]
 [  7  10  32]
 [ 23  34 116]]


In [7]:
##Activity: Matrix calculations and score filtering

"""Given a 5*4 matrix of student scores (rows: Students, columns: subjects),find:
-Average score per student
-Student who scored above 75 in any subject"""


import numpy as np
np.random.seed(0)
student_scores = np.random.randint(50,100,size=(5,4))
print(student_scores)
#Average score per student
print("\nMean marks of the student:",np.mean(student_scores,axis =1))
print("\n")
# Student who scored above 75 in any subject
# high_scores = student_scores[student_scores>75]
# print("Scores more than 75:",high_scores)

for i in range(5):
    scores = student_scores[i]
    found = False
    
    for j in range(4):
        if (scores[j]>75):
            found = True
            break
            
    if found:
        print(f"Student {i+1} has at least one subject marks more than 75")
    else:
        print(f"Student {i+1} does not have any subject marks more than 75")
        
    

[[94 97 50 53]
 [53 89 59 69]
 [71 86 73 56]
 [74 74 62 51]
 [88 89 73 96]]

Mean marks of the student: [73.5  67.5  71.5  65.25 86.5 ]


Student 1 has at least one subject marks more than 75
Student 2 has at least one subject marks more than 75
Student 3 has at least one subject marks more than 75
Student 4 does not have any subject marks more than 75
Student 5 has at least one subject marks more than 75


In [8]:
student_ = np.any(student_scores>75,axis=1)
student_

array([ True,  True,  True, False,  True])

In [ ]:
## Assignment: Analyze Numeric Data and Filter Top 10% Scores

"""Given a list of exam scores for 30 students, write a program to:
- Compute the mean and standard deviation
- Filter scores in the top 10%
"""

In [30]:
import numpy as np
# np.random.seed(0)
st_marks = np.random.randint(50,100, size=30)
print(st_marks)

print("\nMean marks:",np.mean(st_marks))
print("Standard Deviation:",np.std(st_marks))

cutoff_mark =np.percentile(st_marks,90)

top_marks = st_marks[st_marks>cutoff_mark]
print("Top 10% marks: ",top_marks)


[55 83 57 80 58 70 57 53 71 77 94 53 88 70 57 69 81 50 55 77 93 80 59 69
 57 71 87 78 58 93]

Mean marks: 70.0
Standard Deviation: 13.436269323489066
Top 10% marks:  [94 93 93]


In [2]:
#to know the marks of least 10% student

import numpy as np
# np.random.seed(0)
st_marks = np.random.randint(50,100, size=30)
print(st_marks)

print("\nMean marks:",np.mean(st_marks))
print("Standard Deviation:",np.std(st_marks))

cutoff_mark =np.percentile(st_marks,10)

least_marks = st_marks[st_marks<cutoff_mark]
print("Least 10% marks: ",least_marks)


[95 84 65 86 96 88 77 59 87 85 54 70 81 61 87 95 61 86 81 50 94 96 85 75
 51 53 53 99 59 50]

Mean marks: 75.43333333333334
Standard Deviation: 16.261782053500646
Least 10% marks:  [50 51 50]


In [10]:
import numpy as np
# np.random.seed(0)
data = np.array([1,2,3,4])
print(data)
copy_data = data.copy()
print(copy_data)
view_data = data.view()
print(view_data)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [11]:
copy_data[2]=33
print(data)
print(copy_data)

[1 2 3 4]
[ 1  2 33  4]


In [12]:
view_data[1]=22
print(data)
print(view_data)

[ 1 22  3  4]
[ 1 22  3  4]


In [24]:
if data is copy_data:
    print("Yes")
else:
    print("no")

no


In [23]:
if data is view_data:
    print("Yes")
else:
    print("no")

no


In [31]:
np.shares_memory(view_data,data)

True

In [32]:
np.shares_memory(copy_data,data)

False

In [33]:
id(copy_data)

2209636121072

In [34]:
id(data)

2209635660496

In [35]:
id(view_data)

2209635521552

## Join, Split, Sort, Filter, Search

Manipulating the structure and content of arrays is a **core skill in NumPy**.

---

### 🔹 Joining

Putting the contents of two or more arrays into a single array using:

- `np.concatenate()`
- `np.stack()`
  

In [43]:
import numpy as np

a= np.array([1,2,3])
b= np.array([4,5,6])

joined = np.concatenate((a,b))
print(joined)
print(joined.ndim)

[1 2 3 4 5 6]
1


In [39]:
import numpy as np

a= np.array([1,2,3])
b= np.array([4,5,6])

joined = np.stack((a,b))
print(joined)


[[1 2 3]
 [4 5 6]]


In [40]:
joined.ndim

2

### 🔹 Splitting

Breaking one array into multiple arrays using:

- `np.array_split(data, number)` Split 1D or 2D arrays into equal parts
- 

In [55]:
arr_big = np.array([1, 2, 3, 4, 5, 6])

a=np.array_split(arr_big,3)
print(a)
print(a[1])

[array([1, 2]), array([3, 4]), array([5, 6])]
[3 4]


In [54]:
b=np.array_split(arr_big,7)
print(b)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


In [66]:
# --- SORTING ---

unsorted = np.array([3, 1, 2, 5, 4])
sorted_arr = np.sort(unsorted)
print(f"Original: {unsorted}")
print(f"Sorted:   {sorted_arr}")
print("Reversed sorted array is ",sorted_arr[::-1])


Original: [3 1 2 5 4]
Sorted:   [1 2 3 4 5]
Reversed sorted array is  [5 4 3 2 1]


In [68]:
# --- SORTING ---

unsorted = np.array([[5, 4, 6],[ 2, 3,1]])
sorted_arr = np.sort(unsorted)
print(f"Original: {unsorted}")
print(f"Sorted:   {sorted_arr}")
print("Reversed sorted array is ",sorted_arr[::-1])

Original: [[5 4 6]
 [2 3 1]]
Sorted:   [[4 5 6]
 [1 2 3]]
Reversed sorted array is  [[1 2 3]
 [4 5 6]]


In [67]:
# --- SEARCHING ---
unsorted = np.array([3, 1, 4, 2, 5, 4])
idx = np.where(unsorted == 4)
print(f"Index where value is 4: {idx}")

Index where value is 4: (array([2, 5], dtype=int64),)


In [69]:
# Searchsorted (Binary Search) - finds where value should be inserted to maintain order
sorted_base = np.array([1, 3, 5, 7])

insert_idx = np.searchsorted(sorted_base, 4)
print(f"Insert 4 into {sorted_base} at index: {insert_idx}")

Insert 4 into [1 3 5 7] at index: 2


In [71]:
sorted_base[2] =4
sorted_base

array([1, 3, 4, 7])

## 3. Working with Missing Data in NumPy

Unlike **Pandas**, standard **NumPy integer arrays** do not support missing values (`NaN`).  
To work with missing data, the array usually needs to be of type **float** or **object**.

### 🔹 Key Concepts

- **`np.nan`**  
  Represents a missing or undefined value (*Not a Number*).

- **`np.isnan()`**  
  Checks which elements are missing.

- **`np.nansum()`**, **`np.nanmean()`**  
  Perform arithmetic operations while safely ignoring `NaN` values.

In [73]:
import numpy as np
# Create an array with missing data (must be float)
data = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])

print(f"Array with NaNs: {data}")

#detect missing values
bool_miss = np.isnan(data)
print(f"Is Nan?: {bool_miss}")

#Count missing values
print(f"Count of NaNs :{np.sum(bool_miss)}")

Array with NaNs: [ 1.  2. nan  4.  5. nan]
Is Nan?: [False False  True False False  True]
Count of NaNs :2


In [75]:
#3. Standard aggregation fails with NaN
print(f"Standard Sum(fails): {np.sum(data)}")

Standard Sum(fails): nan


In [77]:
#4. Safe aggregation(ignoring nans)
print(f"Safe Sum(nansum): {np.nansum(data)}")
print(f"Safe Mean(nanmean): {np.nanmean(data)}")

Safe Sum(nansum): 12.0
Safe Mean(nanmean): 3.0


In [78]:
# 5. Removing NaNs
clean_data = data[~np.isnan(data)]
print(f"Data with NaNs removed: {clean_data}")

# 6. Filling NaNs with a value (e.g., 0)
filled_data = np.copy(data)
filled_data[np.isnan(filled_data)] = 0
print(f"Data with NaNs filled with 0: {filled_data}")

Data with NaNs removed: [1. 2. 4. 5.]
Data with NaNs filled with 0: [1. 2. 0. 4. 5. 0.]
